[package]
name = "mpc-ecdsa-wasm"
version = "0.2.0"
edition = "2018"
license = "MIT"
description = "Webassembly bindings to multi-party-ecdsa"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
mpc-ecdsa-getrandom-hack = {path = "../../getrandom", version = "*"}
getrandom = {version = "0.1.16", features = ["wasm-bindgen"]}
curv-kzen = {version = "0.9", features = ["num-bigint"], default-features = false}
wasm-bindgen = { version = "0.2.79", features = ["serde-serialize"] }
wasm-bindgen-rayon = "1.0"
rand = { version="0.6.5", features = ["wasm-bindgen"] }
#rand = { version="0.7.3", features = ["getrandom"] }
console_error_panic_hook = "0.1.6"
sha2 = "0.9"
sha3 = "0.10"
serde = {version = "1", features = ["derive"]}
hex = "0.4"
round-based = "0.1"

[dependencies.paillier]
version = "0.4.2"
package = "kzen-paillier"
default-features = false

[dependencies.multi-party-ecdsa]
git = "https://github.com/ZenGo-X/multi-party-ecdsa"
#branch = "master"
default-features = false
rev = "c94065fbf37132dccc7955cf2627866e87c162bf"
version = "*"

[dev-dependencies]
wasm-bindgen-test = "0.3"
